---
title: "Temperature data Rebio Arvoredo e surroundings"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(reshape2)
library(leaflet)
library(ggplot2)
library(vegan)
library(plotly)
library(lubridate)
library(dplyr)
library(readxl)
library(tidyverse)
library(purrr)
library(magrittr)
library(RColorBrewer)
library(gt)

palette(brewer.pal(8, "Set2"))
```

```{r dataread, message=FALSE, warning=FALSE, include=FALSE}

# We import the csv from the folder Data containing all the site's CSV

IC<-read.csv("data/IC.csv",header=TRUE,sep=";", dec=",")
TS<-read.csv("data/TS.csv",header=TRUE,sep=";", dec=",")
FA<-read.csv("data/FA.csv",header=TRUE,sep=";", dec=",")
DE<-read.csv("data/DE.csv",header=TRUE,sep=";", dec=",")
AR<-read.csv("data/AR.csv",header=TRUE,sep=";", dec=",")
IG<-read.csv("data/IG.csv",header=TRUE,sep=";", dec=",")
RN<-read.csv("data/RN.csv",header=TRUE,sep=";", dec=",")
```


Arvoredo Map
======================================================================
```{r map}
###Ilha do Campeche
## For each site we create a summary containing the coordinates, the temperature data and the site name
## get the coordinates of the site (lat,long)
siteCoordsIC = IC %>% #we use the data from IC csv
  dplyr::group_by(Site)%>% #we group the data by site name (IC)
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T)) #we calculate the min, max and mean 

## get temperature information by site (min, max and mean)
siteTempIC = IC %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## We join all the the information in one sheet
SumIC = full_join(siteCoordsIC, siteTempIC) #we join the table to have one unique table 

### Bahía do Farol
## get lat lon
siteCoordsFA = FA %>% 
  dplyr::group_by(Site)%>% 
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempFA = FA %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## join the information together
SumFA = full_join(siteCoordsFA, siteTempFA)#we have to add the depth

###Ilha das Aranhas
## get lat lon
siteCoordsAR = AR %>% 
  dplyr::group_by(Site)%>%
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempAR = AR %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## join the information together
SumAR = full_join(siteCoordsAR, siteTempAR)#we have to add the depth

### Ilha Deserta
## get lat lon
siteCoordsDE = DE %>% 
  dplyr::group_by(Site)%>% 
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempDE = DE %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## ajoin the information in one sheet
SumDE = full_join(siteCoordsDE, siteTempDE)#we have to add the depth

###Toca de Salema
## get lat lon
siteCoordsTS = TS %>%
  dplyr::group_by(Site)%>% 
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempTS = TS %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 


## join the information in one sheet
SumTS = full_join(siteCoordsTS, siteTempTS)#we have to add the depth

###Rancho Norte 
## get lat lon
siteCoordsRN = RN %>% 
  filter(Site != "NA")%>%
  dplyr::group_by(Site)%>%
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempRN = RN %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>% 
  filter(Site != "NA")%>%
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## join the information in one sheet
SumRN = full_join(siteCoordsRN, siteTempRN)#we have to add the depth

###Ilha de Galé
## get lat lon
siteCoordsIG = IG %>% 
  dplyr::group_by(Site)%>% 
  dplyr::summarise(lng = mean(longitude, na.rm=T), 
                   lat = mean(latitude, na.rm=T))

## get temp information by site
siteTempIG = IG %>% dplyr::group_by(Site)%>%  
  dplyr::group_by(Site) %>%
  dplyr::summarise(maxTemp = max(Temp,na.rm=T),minTemp = min(Temp,na.rm = T), meanTemp=mean(Temp,na.rm=T)) 

## join the information in one sheet
SumIG = full_join(siteCoordsIG, siteTempIG)#we have to add the depth


## create a color palette
pal <- colorFactor(palette = c('#e31a1c','#1f78b4','#b2df8a','#33a02c',
                                        '#fb9a99','#a6cee3','#fdbf6f','#ff7f00',
                                        '#cab2d6','#6a3d9a','#ffff99','#b15928'),
                                        domain= c("AR", "DE","DS","ESTL","ESTO",
                                                  "FA", "NL","RN","SA", "SC", 
                                                  "TS","XV"))

## We gather all the site summaries in a single table (Z) that will be used for the map
Z <- rbind(SumTS,SumIG,SumDE,SumRN,SumFA,SumAR,SumIC)

## We create the map by using leaflet package
#the popup provides site/coordinate/temperature data information when clicking on the icon
#cluster allows sites to be grouped according to zoom
leaflet(Z[1:6]) %>% 
  addTiles() %>%
  addMarkers(popup = ~paste0('Site: ',Site,"<br/>Longitude :",lng,"<br/>",'Latitude :',lat,"<br/>",'Min Temp :', minTemp,"<br/>",'Max Temp :',maxTemp,"<br/>",'Mean Temp :',round(meanTemp,digits=3)), 
label = ~paste0(Site), 
  clusterOptions = markerClusterOptions()) %>% 
  addMiniMap(toggleDisplay = T)

```
Temperature summary by Site
======================================================================
```{r}
## we create the summary table and rename the columns
colnames(Z)[2]<-"Longitude"
colnames(Z)[3]<-"Latitude"
colnames(Z)[4]<-"Max Temperature (ºC)"
colnames(Z)[5]<-"Min Temperature (ºC)"
colnames(Z)[6]<-"Mean Temperature (ºC)"
knitr::kable(Z)
```

Temperature graphics by Site
======================================================================
## Column {.tabset}

### Ilha de Campeche

```{r}
## We change the format of the data 
IC$Date=as.Date(IC$Date)
## we change the depth data as factor in order to have different curves depending on the depth
IC$Depth_m <- factor(IC$Depth_m)
## we create the graphic 
ICgraph <-ggplot() + geom_line(data =IC, aes(x = Date, y = Temp, color = Depth_m))
ICgraph <- ICgraph + labs(title="Temperature data from Ilha do Campeche",
                          y = "Temperature",
                          x = "Date",
                          colour = "Depth")
ggplotly(ICgraph)
##we use ggplotly to have an interactive graphic

```

### Ilha Deserta

```{r}
DE$Date=as.Date(DE$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
DE$Depth_m <- factor(DE$Depth_m)
DEgraph<-ggplot() + geom_line(data = DE, aes(x = Date, y = Temp, color = Depth_m))
DEgraph <- DEgraph+ labs(title="Temperature data from Ilha Deserta",
                    y = "Temperature",
                    x = "Date",
                    colour = "Depth")                 
ggplotly(DEgraph)
##we use ggplotly to have an interactive graphic
```

### Ilha das Aranhas
```{r}
AR$Date=as.Date(AR$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
AR$Depth_m <- factor(AR$Depth_m)
ARgraph <-ggplot() + geom_line(data =AR, aes(x = Date, y = Temp, color = Depth_m))
ARgraph <- ARgraph + labs(title="Temperature data from Ilha das Aranhas",
                                y = "Temperature",
                                x = "Date",
                                colour = "Depth")
ggplotly(ARgraph)
##we use ggplotly to have an interactive graphic
```

### Bahia do Farol
```{r}
FA$Date=as.Date(FA$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
FA$Depth_m <- factor(FA$Depth_m)
FArolgraph <-ggplot() + geom_line(data =FA, aes(x = Date, y = Temp, color = Depth_m))
FArolgraph <- FArolgraph + labs(title="Temperature data from Bahia do Farol",
                    y = "Temperature",
                    x = "Date",
                    colour = "Depth")
ggplotly(FArolgraph)
##we use ggplotly to have an interactive graphic
```

### Ilha de Galé
```{r}
IG$Date <- as.Date(IG$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
IG$Depth_m <- factor(IG$Depth_m)
IGgraph <-ggplot() + geom_line(data =IG, aes(x = Date, y = Temp, color = Depth_m))
IGgraph <- IGgraph + labs(title="Temperature data from Ilha de Galé",
                                y = "Temperature",
                                x = "Date",
                                colour = "Depth")
ggplotly(IGgraph)
```
### Toca de Salema
```{r}
TS$Date=as.Date(TS$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
TS$Depth_m <- factor(TS$Depth_m)
TSgraph<-ggplot() + geom_line(data = TS, aes(x = Date, y = Temp, color = Depth_m))
TSgraph <- TSgraph + labs(title="Temperature data from Toca de Salema",
                    y = "Temperature",
                    x = "Date",
                    colour = "Depth")
ggplotly(TSgraph)
```
### Rancho Norte
```{r}
RN$Date=as.Date(RN$Date)
####Change the depth format as a factor and create the graphic with the different depth curves 
RN$Depth_m <- factor(RN$Depth_m)
RNgraph <-ggplot() + geom_line(data =RN, aes(x = Date, y = Temp, color = Depth_m))
RNgraph <- RNgraph + labs(title="Temperature data from Rancho Norte",
                          y = "Temperature",
                          x = "Date",
                          colour = "Depth")
ggplotly(RNgraph)
##we use ggplotly to have an interactive graphic
```
